[theme]
primaryColor = "#1E3A8A"  # Deep Blue (Primary)
backgroundColor = "#E5E7EB"  # Light Gray (Background)
secondaryBackgroundColor = "#3B82F6"  # Bright Blue (Secondary)
textColor = "#1F2937"  # Dark Gray (Text)
font = "sans serif"