[theme]
primaryColor = "#000000"  # Black
backgroundColor = "#2A3C71"  # Purple
secondaryBackgroundColor = "#6A0DAD"  # Dark Blue
textColor = "#FFFFFF"  # White text for readability
font = "Times New Roman"
