[theme]
primaryColor = "#000000"  # Black
backgroundColor = "#2A3C71"  # Lighter Dark Blue
secondaryBackgroundColor = "#FFD700"  # Gold
textColor = "#FFFFFF"  # White text for readability
font = "Times New Roman"
